apiVersion: v1
kind: Pod
metadata: 
  name: ommie
spec:
  containers:
    - name: ommie
      # wrong image name/ private docker image from docker hub
      image: omjaju18/simple-flask:latest
      ports:
        - containerPort: 80

  
    #article - https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

  imagePullSecrets:
    - name: demo1
    