apiVersion: v1
kind: Pod
metadata: 
  name: ommie
spec:
  containers:
    - name: ommie
      image: omjaju18/simple-flask:latest
      ports:
        - containerPort: 80

        #giving less memory so pod gets crahsed as you don't have enough memory to execute pod
      resources:
         limits:
          cpu: "10m"
          memory: "9Mi"

