apiVersion: v1
kind: Pod
metadata: 
  name: ommie
spec:
  containers:
    - name: ommie
      # wrong command use in the docker file of the image - CMD["python", "app1.py"]
      image: omjaju18/simple-flask:latest
      ports:
        - containerPort: 80
      
    